### PR TITLE
Edgerc cleanup

### PR DESCRIPTION
**Pull request by mdb**

### CODE REVIEW

**Comment by JonathanBennett** [comment]
Thanks for the PRs @mdb - rest assured I will merge them, just making sure that all the documentation is up to date and clearing up some tests. Will hopefully get to this by EOW and then pubish Sat/Sun.

Thanks for your amends over the last couple of weeks - It's much appreciated.

**Comment by mdb** [comment]
@JonathanBennett Sounds good - I'll stay posted. Note that the `edgerc-cleanup` changes are _also_ included in the `request-cleanup` branch. You likely will want to assess/merge `edgerc-cleanup` first, then assess/merge `request-cleanup`.

I also plan to refactor & further test `auth.js`, as well as add the previously-discussed `#request` method, though I'll hold tight pending your feedback.

Thanks!

**Comment by JonathanBennett** [comment]
I'm sorry it took me so long to get to this, I've reviewed and am very happy with the changes. Thanks so much @mdb and thanks for your continued contributions. I'll merge in request shortly...

**Comment by mdb** [comment]
Thank you!

**Comment by JonathanBennett** [comment]
Published @mdb - Thanks!

**Pull request merged**
